name: spicyguitaracademy_app
description: An application for learning guitar professionally.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # For Http
  http: ^0.13.3

  # For device info
  device_info_plus: ^3.0.1

  # For state management
  provider: ^5.0.0

  # For PDF
  advance_pdf_viewer: ^2.0.0

  # For rendering SVG Images
  flutter_svg: ^0.22.0

  # Weview
  webview_flutter: 2.0.13
  
  # For Payments with Paystack
  flutter_paystack: ^1.0.5+1

  # For Payments with PayPal
  
  # For selecting file
  file_picker: ^4.1.1
  
  # For Launcher icon
  flutter_launcher_icons: ^0.9.2
  
  # For video player
  video_player: ^2.2.3
  chewie: ^1.2.2
  
  # For audio player
  chewie_audio: ^1.2.0
  
  # For sanitizing possible html string
  sanitize_html: ^2.0.0
  
  # For temporary memory
  shared_preferences: ^2.0.7

  # For caching
  # asset_cache: ^1.0.0+1
  # cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  
  # for in app update
  in_app_update: ^2.0.0
  
  # For adding hyperlinks
  url_launcher: ^6.0.10
  
  # For playing short sounds
  soundpool: ^2.2.0
  
  # For Accordions
  accordion: ^2.1.0

# dependency_overrides:
  # path_provider: ^1.6.27
  # path_provider_windows: ^0.0.4
  # plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/icons/
    - assets/imgs/pictures/
    - assets/audio/congrats_audio.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Italic.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/imgs/icons/spicy_guitar_icon.png"
  # flutter pub run flutter_launcher_icons:main
