import 'package:flutter/material.dart';

class PrivacyPolicy extends StatefulWidget {
  @override
  _PrivacyPolicyState createState() => _PrivacyPolicyState();
}

class _PrivacyPolicyState extends State<PrivacyPolicy> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Privacy Policy'),
        ),
        body: SingleChildScrollView(
          padding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
          child: Text(
            """
            Welcome to the Guitar Tricks learning service (referred to herein as either www.guitartricks.com, the “app”, or the "Site"), owned and operated by Guitar Tricks Inc. ('Company"). Subject to the following Terms of Service ("Terms"), Guitar Tricks provides users of the Site with access to services, including a collection of guitar lessons, guitar and guitar-playing resources, and forums of users and subscribers ("Services").
We reserve the right to add, delete and/or modify any of the terms and conditions contained in this Agreement. In the event of substantive changes to the terms of this Agreement, you will be notified with a notice on the site. If any modification is unacceptable to you, your only recourse is to discontinue use of the Services. Your continued use of the Services following posting of a change notice or new agreement on the Site or notice to you via e-mail, will constitute your binding acceptance of the changes.
1. BINDING EFFECT. This is a binding agreement. By using this services provided in connection with the Site, you agree to abide by these Terms, as Company may amend them from time to time in its sole discretion. No one under 13 is allowed to create an account or use the Services. By using the Services, you state that:
    • You can form a binding contract with Company --- meaning that if you're between 13 and 18, your parent or legal guardian has reviewed and agreed to these Terms; and
    • You will comply with these Terms and all applicable local, state, national and international laws, rules, and regulations.
    • Special notice regarding Citizens and residents of the European Union: In accordance with the European Union’s General Data Protection Regulation (GDPR), Citizens of the EU who are younger than 16-years-old, while they have the legal capacity to enter into agreements, shall nevertheless be prohibited from doing so with Company and from using the Services unless consent to use their Personal Data (their personally identifiable information, such as name, email, phone number, IP address, etc.), which is necessary to effectuate the service agreement herein, is actually given or authorized by the holder of parental responsibility over the child. For more information, visit our Privacy Policy. (https://www.guitartricks.com/privacy.php)
2. PRIVACY POLICY. Company respects your privacy and permits you to control the treatment of your personal information. A complete statement of Company’s current privacy policy can be found by clicking here. Company’s privacy policy is expressly incorporated into this Agreement by this reference.
3. COMPANY SERVICES. Company provides three (3) levels of access to the Site and its Services:
    • Visitor Access. Any visitor to the Site will be able to access only basic information about the Site and the Services of Company.
    • Registered User Access. Site visitors may register to use the Site by providing basic information to Company, and registered users receive limited access to Site Services.
    • Subscriber Access ("Full Access"). Registered users may subscribe to "Guitar Tricks Full Access." Subscriber Access requires periodic payments to take and remain in effect. As a subscriber, you agree to pay for the subscription period selected at the time of purchase. You will receive a confirmation notice upon your original effective date with information about your subscription. You may view current information about your subscription at any time at your account page (https://www.guitartricks.com/account.php). It is your responsibility to review the notice and your account page to ensure that it accurately reflects the requested subscription period.
4. SUBSCRIPTION - AUTOMATIC RENEWAL AND CANCELLATION POLICIES. If you are a subscriber, you agree that your subscription shall renew automatically, and that you authorize automatic renewal of your subscription until it is cancelled. You can cancel the automatic renewal of your subscription at any time. To do so, contact us using any of the methods described at www.guitartricks.com/contact.php and provide your account username or account email address. Your account will be canceled within two (2) business days of receipt and acceptance of your cancellation. Company will refund any payment made within sixty (60) days of the payment date.
5. USERNAME/PASSWORD PROTECTION. Upon registering, you will either choose or be given a username and password that will permit you to access the appropriate level of services for the Site. You agree to take all reasonable steps to protect and ensure the accuracy of any login, password or payment information provided in connection with the Services. You further agree to be the sole user of your username/password and the Services, and to promptly notify Company if this is not the case.
6. USER CONTENT. You hereby grant Company a license to use the materials you post to the Site or Service. By posting, downloading, displaying, performing, transmitting, or otherwise distributing information or other content (“User Content”) to the Site or Service, you are granting Company, its affiliates, officers, directors, employees, consultants, agents, and representatives a license to use User Content in connection with the operation of the Internet business of Company, its affiliates, officers, directors, employees, consultants, agents, and representatives, including without limitation, a right to copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate, and reformat User Content. You will not be compensated for any User Content. You agree that Company may publish or otherwise disclose your name in connection with your User Content. By posting User Content on the Site or Service, you warrant and represent that you own the rights to the User Content or are otherwise authorized to post, distribute, display, perform, transmit, or otherwise distribute User Content.
7. PROHIBITED USES OF THE SITE AND SERVICE. Company imposes certain restrictions on your permissible use of the Site and the Service. You are prohibited from violating or attempting to violate any security features of the Site or Service, including, without limitation, (a) accessing content or data not intended for you, or logging onto a server or account that you are not authorized to access; (b) attempting to probe, scan, or test the vulnerability of the Service, the Site, or any associated system or network, or to breach security or authentication measures without proper authorization; (c) interfering or attempting to interfere with service to any user, host, or network, including, without limitation, by means of submitting a virus to the Site or Service, overloading, “flooding,” “spamming,” “mail bombing,” or “crashing;” (d) using the Site or Service to send unsolicited e-mail, including, without limitation, promotions, or advertisements for products or services; (e) forging any TCP/IP packet header or any part of the header information in any e-mail or in any posting using the Service; (f) threaten, harass, abuse, slander, defame or otherwise violate the legal rights (including, without limitation, rights of privacy and publicity) of third parties; (g) publish, distribute or disseminate any inappropriate, profane, vulgar, defamatory, infringing, obscene, tortious, indecent, unlawful, offensive, immoral or otherwise objectionable material or information or (h) attempting to modify, reverse-engineer, decompile, disassemble, or otherwise reduce or attempt to reduce to a human-perceivable form any of the source code used by Company in providing the Site or Service. Any violation of system or network security may subject you to civil and/or criminal liability.
A. Print and Download Restrictions. The Site may at times contain proprietary and original material licensed from Third Parties. The terms under these licenses may prohibit the downloading and/or printing of such material by users. Company is obliged under such licenses to disable the user's ability to download and/or print such content. Any attempt by you to circumvent these restrictions is a violation of the Terms and may result in termination of service and appropriate legal action.
8. INTELLECTUAL PROPERTY NOTICES. The name "Guitar Tricks" and its logo are trademarks of Company. The Site contains proprietary, original material that is protected by U.S. copyright and international treaties. Company, our instructors and our licensors retain all intellectual property rights with respect to such proprietary, original material. It is understood that anyone who misappropriates the Company's name or content for commercial use, without the express permission of the Company, may subject himself to civil or criminal penalties. Similarly, any commercial publication or exploitation of the Services or any content provided in connection therewith is specifically prohibited and anyone wishing to do so must first request and receive prior written permission from Company.
9. ALLEGED VIOLATIONS. Company reserves the right to terminate your use of the Service and/or the Site. To ensure that Company provides a high quality experience for you and for other users of the Site and the Service, you agree that Company or its representatives may access your account and records on a case-by-case basis to investigate complaints or allegations of abuse, infringement of third party rights, or other unauthorized uses of the Site or the Service. Company does not intend to disclose the existence or occurrence of such an investigation unless required by law, but Company reserves the right to terminate your account or your access to the Site immediately, with or without notice to you, and without liability to you, if Company believes that you have violated any of the Terms of Use, furnished Company with false or misleading information, or interfered with use of the Site or the Service by others.
10. LINKS. Company welcomes links to its www.guitartricks.com web site. You are free to establish a hypertext link to this Site provided that the link does not state or imply any sponsorship or endorsement by Company. Company often links to web sites that are not under its control. Company is not responsible for the contents of any linked site or any link contained in a linked site. Company provides links only as a convenience and the inclusion of any link does not imply endorsement of the web site by Company.
11. DISSEMINATION, DISCONTINUANCE OR MODIFICATION OF SERVICES. Company may change or discontinue any of its Services or its dissemination of the lessons of any instructor, category and type of music, resources and data, and works of specific contributors, at any time and without notice and without liability to you. Company may change or eliminate any transmission method and may change transmission speeds or other signal characteristics. Company, at its sole discretion, may occasionally make modifications to the Site, its servers, and the information, resources and data contained therein, including the Services and/or Company's Full Access content.
12. DISCLAIMER. Please read this Disclaimer carefully before using any of the Services, including subscribing to the Company's Full Access content.
You understand and agree that the Services available on the site are provided on an "as-is" and "as available" basis. Company hereby disclaims any and all warranties with respect to the Services, whether express, implied, statutory or otherwise, including any implied warranties of fitness for a particular purpose, merchantability, accuracy, title and non-infringement. In connection with the foregoing you expressly agree that use of this site is at your sole risk and without any warranty and that such exclusion of warranties is an essential part of the basis on which Company provides the Services.
You expressly agree that use of the Services, including all lessons and content distributed by, downloaded or accessed from or through this Site, is at your sole risk. You understand and agree that you will be solely responsible for any damage to you or your computer system or for any loss of data that results from the use of the Services by you.
Company will make all reasonable efforts to have the Services available on a 24-hour basis, excluding normal network administration and system down time, but if access is suspended or interrupted, liability will be limited to restoring access to the Services as soon as practical.
With respect to merchandise sold or given as gifts on the Site, any references to their retail or market value represent their "estimated market value." Estimated market value means that reasonable good faith efforts have been made by Company to determine actual retail value of the merchandise. Given the rarity and unique qualities of the products, and the lack of available and reliable market data, the values represented on the Site are estimates only and should not be relied upon as true indications of actual retail or market value.
13. LIMITATION ON LIABILITY. Under no circumstances shall Company be liable, whether alleged as a breach of contract, tort (including negligence and strict liability), equity or otherwise, for any cost of cover or substitute service or any indirect, incidental, special or consequential damages arising from or in connection with the use the Services, or resulting from unauthorized access to or alteration of transmissions of lessons or of other information that is sent or received, including but not limited to damages for lost profits, even if Company has been advised of the possibility of such damages.
14. COPYRIGHT INFRINGEMENT. Company has in place certain legally-mandated procedures regarding allegations of copyright infringement occurring on the Site or with the Service. Company has adopted a policy that provides for the immediate suspension and/or termination of any Site or Service user who is found to have infringed on the rights of Company or of a third party, or otherwise violated any intellectual property laws or regulations. Company’s policy is to investigate any allegations of copyright infringement brought to its attention. If you have evidence, know, or have a good faith belief that your rights or the rights of a third party have been violated and you want Company to delete, edit, or disable the material in question, you must provide Company with all of the following information: (a) a physical or electronic signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed; (b) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works; (c) identification of the material that is claimed to be infringed or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Company to locate the material; (d) information reasonably sufficient to permit Company to contact you, such as an address, telephone number, and if available, an electronic mail address at which you may be contacted; (e) a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (f) a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. For this notification to be effective, you must provide it to Company’s designated agent at:
Benjamin Martin
Guitar Tricks Inc
268 Bush St #4400, San Francisco, CA 94104
(855) 394-8482
legal@guitartricks.com
15. INDEMNITY. You agree to indemnify Company for certain of your acts and omissions. You agree to indemnify, defend, and hold harmless Company, its affiliates, officers, directors, employees, consultants, agents, and representatives from any and all third party claims, losses, liability, damages, and/or costs (including reasonable attorney fees and costs) arising from your access to or use of the Site, your violation of these Terms of Use, or your infringement, or infringement by any other user of your account, of any intellectual property or other right of any person or entity. Company will notify you promptly of any such claim, loss, liability, or demand, and will provide you with reasonable assistance, at your expense, in defending any such claim, loss, liability, damage, or cost.
16. DISPUTE RESOLUTION; ARBITRATION.
A. Complaint Process. Any individual may bring complaints relating to Company’s use of Personal Data, or any other matter arising under this Privacy Policy, directly to the company by sending notice of the complaint to the Company’s Consumer Relations Officer at dataprivacy@guitartricks.com. Company shall respond in a reasonable time not to extend beyond 45 days.
B. Good Faith Negotiation; Arbitration. Should a dispute arise between you and Company under this Agreement, we would like to provide both parties with a neutral and cost-effective means of resolving the dispute quickly. Therefore, except for (i) claims for injunctive or equitable relief, (ii) claims regarding intellectual property rights ((i) and (ii) shall be handled directly by filing the matter with the appropriate State and Federal Courts residing in San Francisco, California), or (iii) claims involving anything related to Company’s use, retention, or sharing of Personal Data (which shall be handled according to Section 16 of Company’s Privacy Policy), for any claim arising under this Agreement, either party shall attempt to resolve said dispute first through good faith negotiations. Should that fail, either party may elect to resolve dispute though binding non-appearance-based arbitration under the Commercial Rules of Arbitration of the American Arbitration Association conducted in San Francisco, California. The Arbitrator and the parties must comply with the following rules: (a) the arbitration will be conducted, at the option of the party seeking relief, by telephone, online or based solely on written submissions; (b) the arbitration will not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; and (c) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.
THE PARTIES ACKNOWLEDGE AND AGREE THAT THE FOREGOING DISPUTE RESOLUTION AGREEMENTS RESULT IN EACH PARTY GIVING UP HIS, HER OR ITS RIGHT TO A JURY TRIAL OF ALL ISSUES. EACH PARTY HEREBY EXPRESSLY WAIVES HIS, HER, OR ITS RIGHT TO A JURY TRIAL WITH RESPECT TO ANY AND ALL DISPUTED ISSUES IN ANY MANNER RELATING TO OR ARISING OUT OF THE TERMS AND CONDITIONS OR PERFORMANCE OR NON-PERFORMANCE OF TERMS AND CONDITIONS OF THIS AGREEMENT.
C. No Class Actions. You and Company agree that either of you may bring claims against the other only in your or its individual capacity and not as a plaintiff or class member in any purported class or representative proceeding. Further, you agree that the arbitrator may not consolidate proceedings of more than one person’s claims and may not otherwise preside over any form of a representative or class proceeding.
D. Cause of Action. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or the Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred.
17. GENERAL PROVISIONS
A. Entire Agreement. This Agreement contains the entire understanding of the parties relating to the subject matter hereof. This Agreement cannot be changed or modified except as provided herein.
B. Waiver; Severability. A waiver by either party of any term or condition of this Agreement will not be deemed or construed as a waiver of such term or condition, or of any subsequent breach thereof. If any provision of this Agreement is determined by a court of competent jurisdiction to be unenforceable, such determination shall not affect any other provision hereof, and the unenforceable provision shall be replaced by an enforceable provision that most closely meets the commercial intent of the parties.
C. Binding Effect. This Agreement will be binding on the assigns, heirs, executors, affiliates, agents, personal representatives, administrators, and successors (whether through merger, operation of law, or otherwise) of each of the parties.
D. Notice. Any notice, approval, request, authorization, direction or other communication under this Agreement shall be given in writing and shall be deemed to have been delivered and given for all purposes on the delivery date if sent by electronic mail to the addresses provided to and by you upon registration with Company, or as properly updated, or, in the absence of a valid electronic mail address, via any other method Company may elect in its sole discretion, including, but not limited to, via posting on the Website.
E. Governing Law; Dispute Resolution. This Agreement will be governed and interpreted in accordance with the laws of the State of California applicable to agreements entered into and to be wholly performed in California, without regard to conflict of laws principles. Any and all disputes arising out of this Agreement shall be resolved in the manner set forth in Arbitration clause above.
F. Rights Cumulative. To the extent permitted by applicable law, the rights and remedies of the parties provided under this Agreement are cumulative and are in addition to any other rights and remedies of the parties at law or equity.
G. Headings. The titles and headings used in this Agreement are for convenience only and are not to be considered in construing or interpreting this Agreement.
H. No Third Party Beneficiaries. This Agreement is for the sole benefit of the parties hereto and their authorized successors and permitted assigns. Nothing herein, express or implied, is intended to or shall confer upon any person or entity, other than the parties hereto and their authorized successors and permitted assigns, any legal or equitable right, benefit or remedy of any nature whatsoever under or by reason of this Agreement.
I. Assignment. Company may assign its rights and obligations under this Agreement at any time to any party. You may not assign your rights and/or obligations under this Agreement without obtaining Company's prior written consent.
18. ACKNOWLEDGEMENT. BY USING THE SERVICE OR ACCESSING THE SITE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE AND AGREE TO BE BOUND BY THEM.
            """,
            textAlign: TextAlign.justify,
          ),
        ));
  }
}
